name: AI Tests

on:
  push:
    paths:
      - 'Ai/**'
    branches:
      - '**'
  pull_request:
    paths:
      - 'Ai/**'
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Ai

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test